# https://www.mkdocs.org/user-guide/configuration/
site_name: Mario Vejlupek
site_url: https://www.vejlupek.cz
docs_dir: Site
theme:
  name: material
  logo: _assets/pica-pica-color.png
  favicon: _assets/pica-pica-color.png

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

  palette:
    scheme: slate
    primary: blue grey

plugins:
  - social
