# https://www.mkdocs.org/user-guide/configuration/
site_name: Mario Vejlupek
site_author: Mario Vejlupek
site_description: >-
  Personal website of Mario Vejlupek
site_url: https://www.vejlupek.cz
repo_url: https://github.com/elmariofredo/elmariofredo
docs_dir: Site
theme:
  name: material
  logo: _assets/pica-pica-color.png

  favicon: _assets/pica-pica-color.png

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

  palette:
    scheme: slate
    primary: blue grey

plugins:
  - search
  - social
  - tags:
      tags_file: Topics.md
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - privacy:
      download: !ENV [DOWNLOAD, false]


markdown_extensions:
  - meta
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/elmariofredo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mariovejlupek
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mariovejlupek

nav:
  - About me: README.md
  - Knowledge Base: Knowledge Base.md
  - Topics: Topics.md
