[project]
name = "elmariofredo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-git-revision-date-localized-plugin>=1.3.0",
    "mkdocs-material[imaging]>=9.5.44",
    "mkdocs-minify-plugin>=0.8.0",
]
